spring:
  influxdb:
    url: http://localhost:8086
    username: user
    password: ~
    database: test
    retention-policy: autogen
    connect-timeout: 10
    read-timeout: 30
    write-timeout: 10
    gzip: true
    